#!/bin/bash
FOREGROUND=$(xrdb -query | grep 'color6:'| awk 'NR==1{print $NF}')
ROFI_OPTIONS=()

another=$(echo "LOCK
SUSPEND
LOGOUT
REBOOT
POWEROFF" | awk '{print $(NF-1)}' | rofi -dmenu -i -p "SYSTEM: ")

if [ "$another" == "LOCK" ] ; then
	~/.config/scripts/i3exit lock;
elif [ "$another" == "SUSPEND" ] ; then
	~/.config/scripts/i3exit suspend;
elif [ "$another" == "LOGOUT" ] ; then
	[ $(echo -e "Yes\nNo" | rofi "${ROFI_OPTIONS[@]}" -theme-str "*{accent: #e53714;}" -dmenu -i -p "Are you shure you want to proceed?") == Yes ] && ~/.config/scripts/i3-msg exit || i3exit exit

elif [ "$another" == "REBOOT" ] ; then
	[ $(echo -e "Yes\nNo" | rofi "${ROFI_OPTIONS[@]}" -theme-str "*{accent: #e53714;}" -dmenu -i -p "Are you shure you want to proceed?") == Yes ] && ~/.config/scripts/i3exit reboot

elif [ "$another" == "POWEROFF" ] ; then
	[ $(echo -e "Yes\nNo" | rofi "${ROFI_OPTIONS[@]}" -theme-str "*{accent: #e53714;}" -dmenu -i -p "Are you shure you want to proceed?") == Yes ] && ~/.config/scripts/i3exit poweroff

else
    echo $another
fi
